import Head from "next/head";
import styles from "../styles/Home.module.css";
import TextBar from "../components/textBar";
import Biden from "../components/Biden";
import TwitterShade from "../components/TwitterShade";
import { Text, Stack, Divider } from "@chakra-ui/react";
import Infograph from "../components/infograph";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Top Tweets Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Stack>
          <TextBar />
          <Biden />
          <Text fontSize="3xl">
            If you categorize the Tweets based on the account type that is
            Tweeting, you’ll see the main categories are{" "}
            <a href="#info_anchor">
              {" "}
              <Text as="mark" cursor="grab">
                politics and entertainment.
              </Text>
            </a>
          </Text>
          <TwitterShade />
          <Text fontSize="3xl">
            Interestingly enough, <Text as="i">9 out of 10</Text> of the most
            liked Tweets come from Tweets posted after 2020, during the
            COVID-19. Check out the interactive section below to learn more.
          </Text>
          <br />
          <Divider />
          <br />
          <Infograph />
        </Stack>
      </main>
    </div>
  );
}
